export type { Allergy } from '@interfaces/allergy';
export type { ApiError } from '@interfaces/api_error';
export type { Appointment, AppointmentCreationData } from '@interfaces/appointment';
export type { Coding } from '@interfaces/coding';
export type { Condition } from '@interfaces/condition';
export type { DiagnosticReport } from '@interfaces/diagnostic-report';
export type { DocumentResource } from '@interfaces/document-resource';
export type { Goal } from '@interfaces/goal';
export type { Immunization } from '@interfaces/immunization';
export type { Invoice } from '@interfaces/invoice';
export type { LabImagingReport } from '@interfaces/lab-imaging-report';
export type { Medication } from '@interfaces/medication';
export type { Message } from '@interfaces/message';
export type { PaymentNotice } from '@interfaces/payment-notice';
export type { Patient } from '@interfaces/patient';
export type { Question } from '@interfaces/question';
export type { Schedule, Slot } from '@interfaces/schedule';
export type { Vital } from '@interfaces/vital';
